### PR TITLE
Add some basic modules

### PR DESCRIPTION
**Pull request by adrien2p**
Contains :

- Authentication module
- User module
- DatabaseModule

I propose the following things :

- Sequelize (postgres)
- Umzug for database migration instead of `sequelize.sync()` to avoir drop table
- Passport-jwt

### CODE REVIEW

**Comment by adrien2p** [comment]
I just need to add some tests and add an .env file if that is ok for you.
I am waiting for your feedback before continuing ;)

**Comment by yharaskrik** [comment]
+1 for the sequelize and passport

**Comment by adrien2p** [comment]
I think that we should create a slack room to discuss about what we are doing and avoid duplicating work.

We can also work in concert on certain branch if it necessary to share capabilities.

What do you think about that ?

Because it will be much easier to exchange between us than using email or anything else.

**Comment by yharaskrik** [comment]
Was thinking that would be a good idea. Easier to communicate that way.

**Comment by davguij** [comment]
+1 to Slack. I'll create us a group right away.

FWIW, I also created a basic skeleton at https://github.com/backstopmedia/nest-book-example/pull/3, without really any code in it, just so that we could then divide the work among us.

Maybe you @adrien2p could go through it and incorporate the stuff you find useful from there (if any)?

Also, since we are going to cover several types of DBs/ORMs, I'm thinking it might be good to either a) maintain several branches, on for each ORM or b) create several modules that can then be added/removed from the `AppModule`.

What do you guys think?

**Comment by yharaskrik** [comment]
My vote would be for one per branch, but that is just me, keep it separated and clean.

**Comment by davguij** [comment]
(sidenote) I just invited you guys to the Slack channel.

**Pull request merged**
