### PR TITLE
Dockerize the app

### PR DESCRIPTION
**Pull request by davguij**
`docker-compose up` will now start a local development environment with reload on changes.

### CODE REVIEW

**Comment by patrickhousley** [comment]
Was the reloading working for anyone else? On windows, I had to add `"legacyWatch": true,` to the nodemon config. Just wanted to make sure this was not a Windows issue.

**Comment by davguij** [comment]
Reload works on my Mac without `legacyWatch`. I think it has something to do with the filesystem type of each machine, so each user's mileage may vary.
I will include a note in the `README` as a heads up.

**Comment by patrickhousley** [comment]
@adrien2p @davguij This one needs to be merged into master as well. Also, please update the docker compose to create a postgresql database so users do not need postgresql installed and do not need to perform psql commands.

**Comment by adrien2p** [comment]
I will do that you right ;)

**Pull request merged**
