### PR TITLE
Implementing microservices.

### PR DESCRIPTION
**Pull request by patrickhousley**

### CODE REVIEW

**Comment by adrien2p** [comment]
@patrickhousley maybe should you next time squash your commit locally to rebase master instead of merge master :D

Then it will be merge into master, what do you think ?

**Comment by patrickhousley** [comment]
I have never been a fan of squashing commits on my own teams. We can squash in the PR if that is desired.

**Comment by adrien2p** [comment]
It is an habits, we always squash/rebase in separate branch in my teams ^^ sorry

**Comment by adrien2p** [comment]
It is an habits, we always squash/rebase in separate branch in my teams ^^ sorry

**Pull request merged**
